---
role_name_check: 1
dependency:
  name: galaxy
  options:
    ignore-errors: true
driver:
  name: docker
  options:
    # Example: Map a port from the container to the host
    publish:
      - "2222:22"
    # Example: Mount a volume from the host to the container
    privileged: true
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volume:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: "/lib/systemd/systemd"
platforms:
  - name: instance
    image: "ubuntu:24.04"
    dockerfile: Dockerfile.j2
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    # pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  config_options:
    defaults:
      roles_path: "$HOME/projects/terraform/ansible-de/roles:/tmp"
  inventory:
    group_vars:
      all:
        ssh_port: 22
        ssh_key: "files/key.pub"
        users: "ubuntu"
        user: "ubuntu"
        group: "ubuntu"
