galaxy_info:
  role_name: micro
  namespace: eduarddiov
  author: Eduard Diov
  description: Update all packages to the latest version
  license: license (BSD-3-Clause)

  min_ansible_version: "2.15.1"

  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
        - noble

  galaxy_tags:
    - system
    - apt

dependencies: []