---
# tasks file for roles/upgrade

- name: "Update all packages to the latest version"
  ansible.builtin.apt:
    name: "*"
    state: "latest" 
    update_cache: true
  tags:
    - "skip_ansible_lint"