galaxy_info:
  role_name: micro
  namespace: eduarddiov
  author: Eduard Diov
  description: Install the (Î¼)micro text editor
  license: license (BSD-3-Clause)

  min_ansible_version: "2.15.1"

  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
        - noble

  galaxy_tags:
    - micro
    - editor

dependencies: []