#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/sshd
- name: write hostname using jinja2
  ansible.builtin.template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0644'
  notify:
    - Restart sshd