---
name: 'Publish latest release to Ansible Galaxy'

defaults:
  run:
    working-directory: ./

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: 'Publish to Ansible Galaxy'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Build & Publish collection to Ansible Galaxy
        uses: qsypoq/ansible-galaxy-publish-action@v0.0.3
        with:
          galaxy_token: '${{ secrets.GALAXY_API_KEY }}'
