---
name: 'Publish latest release to Ansible Galaxy'

defaults:
  run:
    working-directory: /

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: 'Publish to Ansible Galaxy'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Ansible Publish
        uses: ansible/ansible-publish-action@v1.0.0
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
