---
name: 'Publish latest release to Ansible Galaxy'

on:
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

jobs:
  build:
    name: 'Publish to Ansible Galaxy'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'galaxy'
        uses: 'ansible/ansible-publish-action@v1.0.0'
        with:
          galaxy_api_key: '${{ secrets.GALAXY_API_KEY }}'
          git_branch: 'main'
