---
name: 'Publish latest release to Ansible Galaxy'

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: 'Publish to Ansible Galaxy'
    runs-on: 'ubuntu:latest'
    container:
        image: docker://ghcr.io/ansible/creator-ee:latest
    defaults:
        run:
           working-directory: /
    steps:
      - name: Ansible Publish
        uses: ansible/ansible-publish-action@v1.0.0
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
